comments/urls.py
from django.urls import path
from comments.views import CommentListView, CommentFormView

app_name = 'comments'

urlpatterns = [
    path('', CommentListView.as_view(), name='all'),
    path('add/', CommentFormView.as_view(), name='add'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from common.views import SystemView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comments.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = SystemView.as_view(template_name='common/errors/pages_error.html', status=404)
handler400 = SystemView.as_view(template_name='common/errors/pages_error.html', status=400)
handler500 = SystemView.as_view(template_name='common/errors/pages_error.html', status=500)

comments/models.py
from mptt.models import MPTTModel, TreeForeignKey

from django.db import models
from uuid import uuid4
from django.utils.translation import gettext_lazy as _
from comments.validators import validate_username, validate_file_type, validate_file_size


def release_upload_to(instance, filename):
    """
    Generates a unique file path for uploaded files.
    The file will be saved to MEDIA_ROOT/comments/author/uuid_string+filename.
    """

    ext = filename.split('.')[-1]
    file_prefix = str(uuid4()).split('-')[0]
    filename = f'{file_prefix}.{ext}'
    return f'comments/{instance.author}/{filename}'


class Comment(MPTTModel):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    author = models.CharField(_('User name'),
                              max_length=255,
                              help_text=_('This value may contain only letters, numbers'),
                              validators=[validate_username,]
                              )
    email = models.EmailField(_('Email address'))
    home_page = models.URLField(_('Home page'), blank=True, null=True)
    text = models.TextField(_('Your comment'))
    file = models.FileField(_('Attach file'),
                            upload_to=release_upload_to,
                            help_text=_('It should be an image or text file.'),
                            blank=True,
                            null=True,
                            validators=[validate_file_type, validate_file_size,]
                            )
    created_at = models.DateTimeField(auto_now_add=True)

    class MPTTMeta:
        order_insertion_by = ['-created_at']

    def __str__(self):
        return self.text

comments/forms.py
from django import forms
from django.utils.html import escape

from .models import Comment
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()

    def clean_text(self):
        text = self.cleaned_data['text']
        # Validate and sanitize HTML tags
        text = escape(text)
        return text

    class Meta:
        model = Comment
        fields = ['author', 'email', 'home_page', 'text', 'file']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 5}),
        }

comments/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import FormMixin
from comments.models import Comment
from .forms import CommentForm
from django.utils.translation import gettext_lazy as _
from django.conf import settings


class CommentListView(ListView):
    model = Comment
    template_name = 'comments/all_comments.html'
    context_object_name = 'comments'
    paginate_by = settings.DEFAULT_PAGE_SIZE  # Adjust the number of comments per page

    def get_queryset(self):
        order_by_element = self.request.GET.get('order_by')
        order_by_element = 'created_at' if not order_by_element else order_by_element
        order_dir_element = self.request.GET.get('order_dir')
        parent_comment = self.request.GET.get('parent')
        if parent_comment:
            messages.info(self.request, 'Left your reply in left form')

        # Default order is ascending, add '-' prefix for descending
        if order_dir_element == 'asc':
            order_by_element = order_by_element
        else:
            order_by_element = f'-{order_by_element}'

        return Comment.objects.filter(level=0).order_by(order_by_element)

    def get_context_data(self, **kwargs):
        """
        Adds additional context data to be passed to the template.
        """
        context = super().get_context_data(**kwargs)
        context['comments_form'] = CommentForm()
        return context


class CommentFormView(FormMixin, View):
    form_class = CommentForm

    def get_success_url(self) -> str:
        """
        Defines the success URL after successfully adding the comment.
        """
        return reverse_lazy('comments:all')

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        parent_id = self.request.POST.get('parent_id')
        new_comment = form.save(commit=False)
        if parent_id:
            new_comment.parent = get_object_or_404(Comment, id=parent_id)
        new_comment.save()
        messages.success(self.request, 'Comment added successfully.')
        return super().form_valid(form)

    def form_invalid(self, form):
        query_params = self.request.GET.dict()
        messages.error(self.request, _("There was an error with your submission. Please correct the errors below."))
        return render(self.request, 'comments/all_comments.html',
                      {'comments_form': form, 'comments': Comment.objects.filter(level=0)})

common/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class SystemView(TemplateView):
    status = ''
    template_name = 'common/errors/pages_misc_error.html'  # Default template

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Define the layout for this module
        # _templates/layout/system.html
        context.update(
            {
                'status': self.status,
            }
        )

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, template_name=self.template_name, status=self.status, context=context)

templates/_base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}{% endblock %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">
        <link type="text/css" href="{% static 'css/_base.css' %}" rel="stylesheet" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="">
            <header class="content-center py-4 text-white">
                <h3 class="text-center">Spa</h3>
            </header>
            <!--            Messages block -->
            <div class="messages m-3">
                {% for message in messages %}
                    <div class="alert alert-dismissible {{ message.tags }}" role="alert">
                        <div>{{ message | safe }}</div>
                        <button type="button"
                                class="btn-close"
                                data-bs-dismiss="alert"
                                aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
            <!-- End of messages block -->
            <!-- Content block -->
            {% block content %}{% endblock %}
            <!-- End of content block -->
            <!-- Footer -->
            <div class="footer content-center text-white py-2 ps-3">
                <p class="mb-0 p-auto">&copy; 2023 Ostroukh Hlib</p>
            </div>
            <!-- End of the footer -->
        </div>
        {% block vendor_js %}
            <!-- Bootstrap CSS styles -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                    crossorigin="anonymous"></script>
        {% endblock vendor_js %}
    </body>
</html>

templates/comments/all_comments.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Comments{% endblock %}
{% block vendor_js %}
    {{ block.super }}
    <!-- Theme CSS styles for comments -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/_base.js' %}"></script>
{% endblock vendor_js %}
{% block content %}
    <div class="row mt-3">
        <div class="col-lg-4">
            <div class="card p-4 m-3">
                <h3>Leave a Comment</h3>
                <form id="commentForm"
                      method="post"
                      action="{% url 'comments:add' %}"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ comments_form|crispy }}
                    {% if comments_form.non_field_errors %}
                        <div class="alert alert-danger">
                            {% for error in comments_form.non_field_errors %}<p>{{ error }}</p>{% endfor %}
                        </div>
                    {% endif %}
                    <input type="hidden" name="parent_id" value="{{ request.GET.parent }}">
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                    <button type="reset" class="btn btn-outline-secondary">Discard</button>
                </form>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card p-4 m-3">
                <div class="d-flex justify-content-between">
                    <div>
                        <!-- Dropdown filter -->
                        <div>
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle"
                                        type="button"
                                        data-bs-toggle="dropdown"
                                        aria-expanded="false">Order by</button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item"
                                           href="?order_by=author&order_dir={{ request.GET.order_dir }}">User name</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           href="?order_by=email&order_dir={{ request.GET.order_dir }}">E-mail</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           href="?order_by=created_at&order_dir={{ request.GET.order_dir }}">Creation time</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div>
                        <button type="button" class="btn btn-secondary">
                            <a class="dropdown-item"
                               href="?order_by={{ request.GET.order_by }}&order_dir=asc">Ascending</a>
                        </button>
                        <button type="button" class="btn btn-secondary">
                            <a class="dropdown-item"
                               href="?order_by={{ request.GET.order_by }}&order_dir=desc">Descending</a>
                        </button>
                    </div>
                </div>
                {% if comments %}
                    <div class="mt-5">
                        {% for comment in comments %}
                            {% include 'partials/_comment.html' with comment=comment %}
                        {% endfor %}
                    </div>
                    <div class="mt-5">
                        {% if page_obj.has_previous or page_obj.has_next %}
                            {% include 'partials/_pagination.html' %}
                        {% endif %}
                    </div>
                {% else %}
                    <p>There are no comments yet...</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/partials/_comment.html
{% load comment_extras %}
{% load crispy_forms_tags %}
<div class="comment mt-1"
     style="margin-left: {{ comment.level|multiply:20 }}px">
    <div class="row border-start"
         style="margin-left: {{ comment.level|multiply:20 }}px">
        <!-- Image column -->
        <div class="col-auto">
            <div class="ava">
                <img class="rounded-circle shadow-1-strong me-3"
                     src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(10).webp"
                     alt="avatar"
                     width="65"
                     height="65" />
            </div>
        </div>
        <!-- Text column -->
        <div class="col">
            <div class="message">
                <div class="info">
                    <span class="fs-6 fw-medium">{{ comment.author }}</span> <span class="small">- {{ comment.created_at|date:"d.m.Y" }} at {{ comment.created_at|date:"H:i" }}</span>
                </div>
                <div class="text">
                    <span>{{ comment.text }}</span>
                </div>
                <div class="actions">
                    <a href="?parent={{ comment.pk }}" class="reply-btn">Reply</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% for child in comment.get_children %}
    {% include 'partials/_comment.html' with comment=child %}
{% endfor %}

templates/partials/_pagination.html
{% load query_params %}
<!-- Pagination Styles -->
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center align-items-center">
        <!-- First page link -->
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
            <a class="page-link"
               href="{% if page_obj.has_previous %}?{% get_query_params %}&page=1{% endif %}"
               aria-label="First">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <!-- Previous page link -->
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
            <a class="page-link"
               href="{% if page_obj.has_previous %}?{% get_query_params %}&page={{ page_obj.previous_page_number }}{% endif %}"
               aria-label="Previous">
                <span aria-hidden="true">&lt;</span>
            </a>
        </li>
        <!-- Page links -->
        <li class="page-item">
            <a class="page-link">&hellip;</a>
        </li>
        {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number or page_num == page_obj.next_page_number or page_num == page_obj.previous_page_number %}
                <li class="page-item {% if page_num == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?{% get_query_params %}&page={{ page_num }}">{{ page_num }}</a>
                </li>
            {% endif %}
        {% endfor %}
        <li class="page-item">
            <a class="page-link">&hellip;</a>
        </li>
        <!-- Next page link -->
        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
            <a class="page-link"
               href="{% if page_obj.has_next %}?{% get_query_params %}&page={{ page_obj.next_page_number }}{% endif %}"
               aria-label="Next">
                <span aria-hidden="true">&gt;</span>
            </a>
        </li>
        <!-- Last page link -->
        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
            <a class="page-link"
               href="{% if page_obj.has_next %}?{% get_query_params %}&page={{ page_obj.paginator.num_pages }}{% endif %}"
               aria-label="Last">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
<!-- Pagination Styles -->